spring.application.name=studylog

spring.datasource.url=jdbc:postgresql://localhost:5432/studylog
spring.datasource.username=studylog
spring.datasource.password=studylog

spring.jpa.hibernate.ddl-auto=update